apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-conversao-temperatura
spec:
  selector:
    matchLabels:
      app: app-conversao-temperatura
  template:
    metadata:
      labels:
        app: app-conversao-temperatura
    spec:
      containers:
      - name: app-conversao-temperatura
        image: brunogomesmottta/conversao-temperatura:v1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: app-conversao-temperatura
spec:
  selector:
    app: app-conversao-temperatura
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000
  type: LoadBalancer    